name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  
  # Allow manual deployment
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to push to gh-pages branch
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create static API files
        run: |
          mkdir -p dist/api
          node -e "
            const fs = require('fs');
            const path = require('path');
            
            // Static stats data
            const statsData = {
              totalPushups: 1250,
              totalSquats: 980,
              totalSitups: 870,
              longestStreak: 14,
              completionRate: 78,
              daysCompleted: 47,
              totalDays: 60,
              currentStreak: 7,
              challengeProgress: 26
            };
            
            fs.writeFileSync('./dist/api/stats.json', JSON.stringify(statsData));
            console.log('Created static API files successfully');
          "
      
      - name: Build client
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Remove this line if you don't have a custom domain
          # cname: yourdomain.com